### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by gaxnys** [AppsFlyerSDK/appsflyer-oaid#7]
Hi!

I don't see a `LICENSE` file in this repo. Could you please add this, to make it clear what license applies for this code?

**Comment by gaxnys** [comment]
Also, what licenses apply for the Huawei dependency, the Xiaomi dependency, and the msa_mdid dependency? (And where are the .jar and .aar files from?)

**Comment by af-fess** [comment]
#6
