### ISSUE TITLE
D8 errors

### ISSUE THREAD

**Issue by BinQi** [AppsFlyerSDK/appsflyer-oaid#9]
Cannot create android app from an archive 'app/build/intermediates/transforms/proguard/release/0.jar' containing both DEX and Java-bytecode content

**Comment by af-fess** [comment]
We will check it out, thanks

**Comment by afdima** [comment]
Can you provide a sample project that reproduces the issue?
Did you check https://stackoverflow.com/search?q=containing+both+DEX+and+Java-bytecode+content?
Maybe you need to bump an android gradle plugin version.

**Comment by afdima** [comment]
- Update android gradle plugin to the latest version
- Update all modules to java 8
- add android.useNewApkCreator=false to gralde.properties

**Comment by k4dima** [comment]
Update android gradle plugin to 3.6.3
